# Generated by Django 4.2.4 on 2026-09-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_records_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='isBeingReared',
            field=models.BooleanField(default=True),
        ),
    ]
