# Generated by Django 4.2.4 on 2026-09-25 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_pet_isbeingreared'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date published')),
                ('state', models.CharField(choices=[('feed', '피딩'), ("don't feed", '피딩 거부'), ('wait feed', '피딩 대기')], max_length=15)),
                ('petId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.pet')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
