# Generated by Django 4.2.4 on 2026-09-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='state',
            field=models.CharField(choices=[('피딩', '피딩'), ('피딩 거부', '피딩 거부'), ('피딩 대기', '피딩 대기'), ('기록 없음', '기록 없음')], default='기록 없음', max_length=15),
        ),
    ]
