# Generated by Django 4.2.4 on 2026-09-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_dashboard_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
